### PR TITLE
Changed error to use defined arg

### LINKED ISSUE #857: CloudGraphsDFG AddDataEntry failing when ppe is missing
Run this function to reproduce:

```
# Assemble test graph
    testUser::String = "testUser"
    testRobot::String = "testRobot"
    testSession::String = "testSession"*string(uuid4())[1:7]
    testVariableLabel::Symbol = Symbol("testVariable")
    testBlobLabel::String = "testBlob"
    neo4jConnection = Neo4j.Connection("localhost", port=...., user="....", password="....")
    neo4jDfg = CloudGraphsDFG{SolverParams}(neo4jConnection, testUser, testRobot, testSession, "Navability Cloud", solverParams=SolverParams())
    addVariable!(neo4jDfg, testVariableLabel, Pose2)

# Test add data entry
entry = BlobStoreEntry(
      testBlobLabel,
      UUID("123e4567-e89b-12d3-a456-426614174000"),
      Symbol("Test"),
      "Test",
      "Test",
      "Test",
      "application/json",
      now(tz"UTC")
    )
    addDataEntry!(dfg,Symbol(msg["nodeLabel"]),entry)

savedDataEntry = getDataEntry(neo4jDfg, testVariableLabel, testBlobLabel)
    return savedDataEntry !== nothing

```
Error is as shown:

```
neo4j-testset: Error During Test at .....
  Test threw exception
  Expression: testAddDataEntry()
  UndefVarError: ppe not defined
  Stacktrace:
   [1] _matchmergeVariableSubnode!(dfg::CloudGraphsDFG{SolverParams}, variablekey::Symbol, nodeLabels::Vector{String}, subnode::BlobStoreEntry, relationshipKey::Symbol; addProps::Dict{String, String}, currentTransaction::Nothing)
     @ DistributedFactorGraphs.CloudGraphsDFGs ~/.julia/packages/DistributedFactorGraphs/8zj9m/src/CloudGraphsDFG/services/CommonFunctions.jl:325
   [2] addDataEntry!(dfg::CloudGraphsDFG{SolverParams}, label::Symbol, bde::BlobStoreEntry; currentTransaction::Nothing)
     @ DistributedFactorGraphs.CloudGraphsDFGs ~/.julia/packages/DistributedFactorGraphs/8zj9m/src/CloudGraphsDFG/services/CloudGraphsDFG.jl:690
   [3] addDataEntry!
     @ ~/.julia/packages/DistributedFactorGraphs/8zj9m/src/CloudGraphsDFG/services/CloudGraphsDFG.jl:687 [inlined]
   [4] (::var"#run#3"{CloudGraphsDFG{SolverParams}})(msg::Dict{String, Any})
     @ Main ~/Workspace/NavAbility/cloud-system/services/fg/worker/src/handlers.jl:68
```

### PR DESCRIPTION
**Pull request by jim-hill-r**
- Fixes #857

Will need to cherry-pick into master.

### CODE REVIEW

File: src/CloudGraphsDFG/services/CommonFunctions.jl [hunk 1]
```diff
@@ -322,8 +322,8 @@ function _matchmergeVariableSubnode!(
         result = commit(tx)
     end
     length(result.errors) > 0 && error(string(result.errors))
-    length(result.results[1]["data"]) != 1 && error("Cannot find subnode '$(ppe.solveKey)' for variable '$variablekey'")
-    length(result.results[1]["data"][1]["row"]) != 1 && error("Cannot find subnode '$(ppe.solveKey)' for variable '$variablekey'")
+    length(result.results[1]["data"]) != 1 && error("Cannot find subnode '$(subnode)' for variable '$variablekey'")
+    length(result.results[1]["data"][1]["row"]) != 1 && error("Cannot find subnode '$(subnode)' for variable '$variablekey'")
```
Comment (dehann) [inline src/CloudGraphsDFG/services/CommonFunctions.jl:326]: The issue does seem to be `ppe` object is not in here, likely a copy paste mistake.  Printing out the `$subnode` like this will work.  I'm not sure if we have to print out the whole thing, because it could be large.  So I'd also be happy to just do:

```suggestion
    length(result.results[1]["data"][1]["row"]) != 1 && error("Cannot find desired subnode::$(typeof(subnode)) for variable '$variablekey'")
```

**Review by dehann — COMMENTED** [review]
slight variation suggested, print the typeof instead so the msg is shorter?  Don't think it serious this way or that/

**Review by Affie — APPROVED** [review]

File: src/CloudGraphsDFG/services/CommonFunctions.jl [hunk 2]
```diff
@@ -322,8 +322,8 @@ function _matchmergeVariableSubnode!(
         result = commit(tx)
     end
     length(result.errors) > 0 && error(string(result.errors))
-    length(result.results[1]["data"]) != 1 && error("Cannot find subnode '$(ppe.solveKey)' for variable '$variablekey'")
-    length(result.results[1]["data"][1]["row"]) != 1 && error("Cannot find subnode '$(ppe.solveKey)' for variable '$variablekey'")
+    length(result.results[1]["data"]) != 1 && error("Cannot find subnode '$(subnode)' for variable '$variablekey'")
```
Comment (dehann) [inline src/CloudGraphsDFG/services/CommonFunctions.jl:325]:
```suggestion
    length(result.results[1]["data"]) != 1 && error("Cannot find desired subnode::'$(typeof(subnode))' for variable '$variablekey'")
```
