### PR TITLE
proper deprecation listSolvekeys,

### LINKED ISSUE #608: What happened to listSolvekeys?????
Deprecation warning or something? 
```julia
julia> listSolvekeys(fg)
ERROR: UndefVarError: listSolvekeys not defined
Stacktrace:
 [1] top-level scope at REPL[5]:1
```

### PR DESCRIPTION
**Pull request by dehann**
fix #608

### CODE REVIEW

File: src/Deprecated.jl [hunk 1]
```diff
@@ -5,6 +5,11 @@
 ##==============================================================================
 ## Remove in 0.11
 ##==============================================================================
+
+export listSolvekeys
```
Comment (Affie) [inline src/Deprecated.jl:9]: FIY @deprecate automatically exports the name

Comment (dehann) [reply src/Deprecated.jl:9]: oh, didnt know that thanks!
