### PR TITLE
buildSubgraph fix and testing 

### LINKED ISSUE #458: Fix typeof(LightDFG(params=getSolverParams(dfg)))
Fix typeof(LightDFG(params=getSolverParams(dfg))) to not make an extra object that is not used

_Originally posted by @Affie in https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/442/review_comment/create_

### PR DESCRIPTION
**Pull request by Affie**
Fix #458 and testing xref #442 
cc @dehann

### CODE REVIEW

File: src/services/AbstractDFG.jl [hunk 1]
```diff
@@ -979,13 +979,12 @@ function buildSubgraph(::Type{G},
...
-# Perhaps IIF.InMemDFGType should perhaps be incorporated as a DFG value, but this has been much debated in the past and hence just left as breadcrum.
-buildSubgraph(dfg::AbstractDFG,
-              variableFactorLabels::Vector{Symbol},
-              distance::Int=1;
-              solvable::Int=0,
-              sessionId::String = "",
-              kwargs...) = buildSubgraph(typeof(LightDFG(params=getSolverParams(dfg))), dfg, variableFactorLabels, distance, solvable=solvable, sessionId=sessionId, kwargs...)
+function buildSubgraph(dfg::AbstractDFG,
+                       variableFactorLabels::Vector{Symbol},
+                       distance::Int=0;
```
Comment (Affie) [inline src/services/AbstractDFG.jl:984]: distance must default to 0 to be compatible with the API

Comment (dehann) [reply src/services/AbstractDFG.jl:984]: Hi @Affie, `distance=1` is most compatible with history of `buildSubgraphFromLabels` that would (from only variable labels) automatically include all factors of inclusive variables.  Need to fix IIF to include the change, thanks.

Comment (dehann) [reply src/services/AbstractDFG.jl:984]: oh you already did thanks JuliaRobotics/IncrementalInference.jl#704
