### PR TITLE
deserialize vartype{T} fix #671

### LINKED ISSUE #671: Cannot deserialize Templated VarTypes
MWE:
```
using IncrementalInference


julia> DFG.getTypeFromSerializationModule("IncrementalInference.ContinuousEuclid{3}")
┌ Error: Unable to deserialize soft type IncrementalInference.ContinuousEuclid{3}
└ @ DistributedFactorGraphs ~/.julia/dev/DistributedFactorGraphs/src/services/Serialization.jl:90
┌ Error: UndefVarError: ContinuousEuclid{3} not defined
│ Stacktrace:
│  [1] getTypeFromSerializationModule(::String) at /home/dehann/.julia/dev/DistributedFactorGraphs/src/services/Serialization.jl:87
│  [2] top-level scope at REPL[7]:1
│  [3] eval(::Module, ::Any) at ./boot.jl:331
│  [4] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
│  [5] repl_backend_loop(::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
│  [6] start_repl_backend(::REPL.REPLBackend, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
│  [7] run_repl(::REPL.AbstractREPL, ::Any; backend_on_current_task::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
│  [8] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
│  [9] (::Base.var"#807#809"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:399
│  [10] #invokelatest#1 at ./essentials.jl:710 [inlined]
│  [11] invokelatest at ./essentials.jl:709 [inlined]
│  [12] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:383
│  [13] exec_options(::Base.JLOptions) at ./client.jl:313
│  [14] _start() at ./client.jl:506
└ @ DistributedFactorGraphs ~/.julia/dev/DistributedFactorGraphs/src/services/Serialization.jl:94
```

------

## Troubleshooting

Looks like the problem might be with:
```julia
julia> getfield(IncrementalInference, Symbol("ContinuousEuclid{3}"))
ERROR: UndefVarError: ContinuousEuclid{3} not defined
Stacktrace:
 [1] top-level scope at REPL[9]:1

julia> getfield(IncrementalInference, Symbol("ContinuousEuclid"))
ContinuousEuclid
```

Solution PR coming soon

### PR DESCRIPTION
**Pull request by dehann**
bump v0.10.6, close #671

### CODE REVIEW

File: src/services/Serialization.jl [hunk 1]
```diff
@@ -84,7 +84,16 @@ function getTypeFromSerializationModule(softtypeString::String)
         else
             m = Main
         end
-        return getfield(m, Symbol(split_st[end]))        
+        noparams = split(split_st[end], r"{") 
+        ret = if 1 < length(noparams)
+            # fix #671, but does not work with specific module yet
```
Comment (Affie) [inline src/services/Serialization.jl:89]: I think this constructor might work https://github.com/JuliaRobotics/IncrementalInference.jl/blob/4097cda7e0f6abcdf003e16c06f05e772b352874/src/Variables/DefaultVariables.jl#L46

Comment (dehann) [reply src/services/Serialization.jl:89]: HI -- sure, we can improve that on update of serialization -- just need a solution for any VarType{T} at this point.
